# Generated by Django 5.1.15 on 2026-08-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('included_credits', models.PositiveIntegerField()),
                ('overage_rate_per_push', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUBSCRIPTION_CHARGE', 'Subscription charge'), ('STK_CREDIT_CONSUMED', 'STK credit consumed'), ('OVERAGE_TOPUP', 'Overage top-up'), ('B2C_COMMISSION', 'B2C commission')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='vault.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='vault.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('renews_at', models.DateTimeField()),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='vault.merchant')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptiontier')),
            ],
        ),
    ]
