# Generated by Django 5.1.15 on 2026-08-03 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('settlement_type', models.CharField(choices=[('DIRECT', 'Direct to merchant paybill/till'), ('CUSTODIAL_B2C', 'Custodial — payout via B2C')], max_length=20)),
                ('shortcode', models.CharField(blank=True, max_length=20, null=True)),
                ('account_ref_format', models.CharField(blank=True, max_length=100, null=True)),
                ('_passkey_encrypted', models.TextField(blank=True, db_column='passkey_encrypted', null=True)),
                ('payout_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('api_public_key', models.CharField(max_length=64, unique=True)),
                ('allowed_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
